---
# defaults for tomcat role

var_TomcatHome: '/opt/tomcat'
var_TomcatUser: 'tomcat'
var_TomcatGroup: 'tomcat'

var_TomcatDownloadURL: 'http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.15/bin/apache-tomcat-8.5.15.tar.gz'
var_TomcatArchiveFile: 'apache-tomcat-8.5.15.tar.gz'
var_TomcatArchiveDir: '{{ var_TomcatHome }}/apache-tomcat-8.5.15'

var_Client: '{{ clienthome }}'
var_TomcatClientDir: '{{ clienthome }}'



var_TomcatStatusUser: 'tomcat_status'
var_TomcatStatusPwd: 'ansible'
var_TomcatAdminUser: 'tomcat_admin'
var_TomcatAdminPwd: 'ansible'

var_TomcatServerPort: '{{ servicehostport }}'
var_TomcatHTTPPort: '{{ apphostport }}'


var_firewalld:
#HTTP
  - port: '{{ var_TomcatHTTPPort }}/tcp'
# #HTTPS
#   - port: '{{ var_TomcatHTTPSPort }}/tcp'
# #AJP
#   - port: '{{ var_TomcatAJPPort }}/tcp'
# #JMX
#   - port: '{{ var_TomcatJMXPort }}/tcp'
# #JMX-RMI
#   - port: '{{ var_TomcatJMXRMIPort }}/tcp'

var_TMPDir: '/opt/tmp'
var_TMP: '/opt/tmp'

...
