---
#Setup local Tower server

- hosts: localhost
  become: yes
  gather_facts: no

  tasks:

  # Remove Demo Project, Inventory, and Template
  - name: Remove Demo Template
    tower_job_template:
      name: "Demo Inventory"
      job_type: run
      project: "Demo Project"
      playbook: "hello world.yml"
      state: absent
    ignore_errors: yes

  - name: Remove Demo Project
    tower_project:
      name: "Demo Project"
      state: absent

  - name: Remove Demo Inventory
    tower_inventory:
      name: "Demo Inventory"
      organization: "Default"
      state: absent

  - name: Add Tower host
    tower_host:
      name: localhost
      description: "Local Tower Host"
      inventory: "Local"
      state: present

  - name: Add Hello World Template
    tower_job_template:
      name: "Hello Local World"
      description: "Run Hello World on Tower Server"
      job_type: run
      project: "Local"
      playbook: "hello_world.yml"
      inventory: Local
      machine_credential: vagrant
      state: present

  - name: Launch Hello World
    tower_job_launch:
      job_template: "Hello Local World"
      credential: vagrant
      inventory: Local
    register: hello_job


...